code_style:
  default: [codespell,drupal,drupalpractice]
deploy:
  test:
    robin: TRUE
    type:
      name: "drupal-7"
      settings:
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        site-name: "Drupal DB Deploy"
        site-mail: "noreply@{domainname}"
