code_style:
  default: [codespell,drupal,drupalpractice]
deploy:
    robin: "true"
    dir: '{home}/git.lc'
    init: '{home}/git.lc/scripts/init_deploy.sh'
    before: '{home}/git.lc/scripts/before_deploy.sh'
    after: '{home}/git.lc/scripts/after_deploy.sh'