code_style:
  default:
    - codespell
    - drupal
    - drupalpractice
deploy:
  master:
    robin: TRUE
    type:
      name: "drupal-7"
      settings:
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        site-name: "Drupal DB Deploy"
        site-mail: "noreply@{domainname}"
    contexts:
      - gitlc/codestyle/branch
      - gitlc/codestyle/commit
  7.x:
    server: "karma.vps-private.net"
    user: "d7"
    type:
      name: "custop"
    dir: '{home}/github/dd/{branch}'
  test:
    robin: TRUE
    type:
      name: "drupal-7"
      settings:
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        site-name: "Drupal DB Deploy"
        site-mail: "noreply@{domainname}"
    contexts:
      - gitlc/codestyle/branch
      - gitlc/codestyle/commit
  pull_request:
    robin: TRUE
    type:
      name: "drupal-7"
      settings:
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        site-name: "Drupal DB Deploy"
        site-mail: "noreply@{domainname}"
    contexts:
      - gitlc/codestyle/pr
      - gitlc/codestyle/commit
